### ISSUE TITLE
JSON Validator responds with "Valid JSON" but output file is different

### ISSUE THREAD

**Issue by olderthandirt5** [CMSgov/price-transparency-guide-validator#44]
I ran the Validator against a provider-reference file and then again to an output file:

> PS C:\cms\price-transparency-guide-validator> cms-mrf-validator validate c:\cms\data\3B_MRF_provider-reference.json v1.0.0 -t provider-reference
> Input JSON is valid.
> 
> PS C:\cms\price-transparency-guide-validator> cms-mrf-validator validate c:\cms\data\3B_MRF_provider-reference.json v1.0.0 -t provider-reference -o 3Bvalidation.txt

Output file contains:

> Input is not a valid JSON
> Error(offset 32529): The document root must not be followed by other values.
> Input JSON is valid.

I changed the extension of the input to be able to upload it.

Will load different files to demonstrate the issue.

**Comment by olderthandirt5** [comment]
Replaced demo files, shows same issue:
[2validation.txt](https://github.com/CMSgov/price-transparency-guide-validator/files/8476455/2validation.txt)
[2_MRF_provider-reference.txt](https://github.com/CMSgov/price-transparency-guide-validator/files/8476478/2_MRF_provider-reference.txt)
e

**Comment by mint-thompson** [comment]
Thank you for reporting this. The input you provided should be reporting as not valid, since it contains multiple root nodes. The later output indicating that the input is valid should not be appearing. The team will be fixing this as soon as possible.
