### ISSUE TITLE
Exit code 0 when JSON is invalid

### ISSUE THREAD

**Issue by ahwitz** [CMSgov/price-transparency-guide-validator#55]
This may be a platform issue, as I'm (unfortunately) on Windows for debugging.

We're trying to incorporate the validator into an existing workflow, and it'd be helpful to parse the process exit code as being zero/nonzero to determine if the validation was successful. Would it be possible to update the exit code to be something other than 0 if validation failed, or does that risk breaking too much? 

If memory serves, this is something I was able to rely on with `xmllint` in the past, so it should hopefully be in convention for validation tools, but don't quote me on that...

(also, as part of this, would be nice to have the "invalid _____" diag written to stderr instead of stdout, but that's far less important to me)

**Comment by mint-thompson** [comment]
Currently, a 0 exit code is always returned. But, it sounds like it would be useful for non-zero codes to be returned when validation fails, so I will discuss with the team about adding this to the validator.

**Comment by olderthandirt5** [comment]
That is very close to what I was trying, but I introduced a bug along the way. :-(

This is the function I got to work:

`
const exec = util.promisify(require('child_process').exec);

async function validateFile(path, fileType, outputPath) {
  const { stdout, stderr, err } = await exec('cms-mrf-validator validate ' + path + ' v1.0.0 -t ' + fileType + ' -o ' + outputPath );
  if (err) {
    console.log(err);
    return;
  }  
}`
Thanks!!

**Comment by mint-thompson** [comment]
@ahwitz I've opened PR #62 that I think will help with this. If you have time, please take a look at it and see if it looks like the changes to exit codes meet your expectations.

**Comment by ahwitz** [comment]
@mint-thompson - looks great, and utils.ts:110-ish is exactly what we were looking for. Only because I saw those lines: there may be some people out there who are looking for `stderr` output instead of/in addition to error codes, and making [108/109](https://github.com/CMSgov/price-transparency-guide-validator/pull/62/files#diff-39b2554fd18da165b59a6351b1aafff3714e2a80c1435f2de9706355b4d32351R108) a `console.error` instead of `console.log` might help, but the exitCode = 1 is more than enough for us. Thanks a ton!
