### ISSUE TITLE
Docker container orphans

### ISSUE THREAD

**Issue by glsobeck** [CMSgov/price-transparency-guide-validator#65]
Can you add at least --rm to the docker command so that we don't end up with orphaned containers? I didn't notice this until today my Docker desktop instance on Mac OSX was loading 100s of container orphans into a list. This really slows down my boot processes on Monday mornings.

**Comment by glsobeck** [comment]
You can remove them via `docker rm -vf $(docker ps -qa)` Right now it's the only way to deal with them w/o spending effort into pattern matching output w/o -q arg in `docker ps`

**Comment by shaselton-usds** [comment]
@mint-thompson would it be possible to take a peek into this?

**Comment by olderthandirt5** [comment]
@glsobeck Thanks for that snippet. I found that I had over 1000 orphan containers, and will probably create that many each month.

**Comment by mint-thompson** [comment]
@glsobeck Thank you for reporting this issue. A pull request has been created that incorporates your recommendation to add the `--rm` flag.
