### ISSUE TITLE
Git submodule

### ISSUE THREAD

**Issue by timrburnham** [CMSgov/price-transparency-guide-validator#69]
Should rapidjson and tclap libraries be linked to their upstream sources and pinned to specific versions in source control?

One approach is git submodule. This is a bit of a project re-org, but I will submit a PR for review.

**Comment by shaselton-usds** [comment]
@timrburnham Thanks for the PR -- took a look and everything appears to be running well though I did have to run a few git submodule commands before everything played nicely. I left a comment in the PR concerning that.

Thanks again.

**Comment by shaselton-usds** [comment]
Just following up on this -- thanks for the input and we merged in the changes!

Thanks again!
